globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=false"
  - "--log.level=DEBUG"


# Deployment
deployment:
  replicas: 2
  enabled: true
  annotations: {}
  podAnnotations: {}
  additionalContainers: {}
  initContainers: {}

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Resource limits
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

# Ports
ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true

# Ingress
ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesIngress:
    enabled: true
  kubernetesCRD:
    enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}


metrics:
  enabled: true
